# Generated by Django 5.2.7 on 2025-10-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_rename_user_perfil_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='date_birth',
            new_name='data_nascimento',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cpf',
            field=models.CharField(help_text='digite apenas números', max_length=11, verbose_name='CPF'),
        ),
    ]
