# Generated by Django 5.2.7 on 2025-10-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_alter_produto_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_exibicao',
            field=models.FloatField(verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_promocional',
            field=models.FloatField(verbose_name='Preço Promocional'),
        ),
    ]
