# Generated by Django 5.2.7 on 2025-10-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_alter_produto_preco_exibicao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_promocional',
            field=models.FloatField(blank=True, verbose_name='Preço Promocional'),
        ),
    ]
