# Generated by Django 5.2.7 on 2025-10-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0007_alter_produto_preco_promocional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_promocional',
            field=models.FloatField(blank=True, default=0, verbose_name='Preço Promocional'),
        ),
    ]
